# This workflow automates the build process and artifact uploading for an Android app.

name: Android CI/CD

on:
  # This allows you to manually trigger the workflow from the GitHub UI.
  workflow_dispatch:

  push:
    branches:
      - main

  release:
    types:
      - created
      - published

jobs:
  build_and_upload_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > passcodes-staging.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.STAGING_KEYSTORE_BASE64 }}

      - name: Decode Keystore Properties
        run: |
          echo "$KEYSTORE_PROPERTIES_BASE64" | base64 --decode > staging-keystore.properties
        env:
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.STAGING_KEYSTORE_PROPERTIES_BASE64 }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      # Step 4: Build the Android app based on the trigger.
      # This step uses an 'if-elif' conditional to determine the correct build variant.
      - name: Build APK based on trigger
        id: build_apk
        run: |
          BUILD_VARIANT=""
          APK_PATH=""

          # Determine the build variant based on the triggering event.
          if [[ "${{ github.event_name }}" == "release" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Triggered by release or manual dispatch. Building release variant."
            BUILD_VARIANT="release"
            ./gradlew assembleRelease
            APK_PATH=app/build/outputs/apk/release/app-universal-release-unsigned.apk
          else
            echo "Triggered by push to 'main' branch. Building staging variant."
            BUILD_VARIANT="staging"
            ./gradlew assembleStaging
            APK_PATH=app/build/outputs/apk/staging/app-universal-staging.apk
          fi

          # Set the output variables for the next steps.
          echo "build_variant=${BUILD_VARIANT}" >> $GITHUB_OUTPUT
          echo "apk_path=${APK_PATH}" >> $GITHUB_OUTPUT
          echo "Found APK at: ${{ steps.build_apk.outputs.apk_path }}"

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_apk.outputs.build_variant }}-apk
          path: ${{ steps.build_apk.outputs.apk_path }}
          if-no-files-found: error
